version: '3'
services:
  petsla_db_container:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: petsla
      MONGO_INITDB_ROOT_PASSWORD: petsla
    ports:
      - 27027:27017
    volumes:
      - petsla_db_container:/data/db

volumes:
  petsla_db_container:
